"""initial_schema

Revision ID: 19e49b831ac9
Revises:
Create Date: 2026-09-25 10:27:23.210370

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19e49b831ac9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_folder", sa.String(length=1024), nullable=False),
        sa.Column("output_folder", sa.String(length=1024), nullable=False),
        sa.Column("source_language", sa.String(length=10), nullable=True),
        sa.Column("target_language", sa.String(length=10), nullable=False),
        sa.Column("glossary_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "episodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("source_file", sa.String(length=1024), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "DETECTING_LANGUAGE",
                "EXTRACTING_AUDIO",
                "TRANSCRIBING",
                "DETECTING_SPEAKERS",
                "TRANSLATING",
                "REVIEW",
                "GENERATING_SUBTITLES",
                "GENERATING_TTS",
                "MIXING_AUDIO",
                "RENDERING",
                "QC",
                "DONE",
                "FAILED",
                "PAUSED",
                name="episodestatus",
            ),
            nullable=False,
        ),
        sa.Column("detected_language", sa.String(length=10), nullable=True),
        sa.Column("language_confidence", sa.Float(), nullable=True),
        sa.Column("extracted_audio_path", sa.String(length=1024), nullable=True),
        sa.Column("transcript_path", sa.String(length=1024), nullable=True),
        sa.Column("diarization_path", sa.String(length=1024), nullable=True),
        sa.Column("translation_path", sa.String(length=1024), nullable=True),
        sa.Column("subtitle_srt_path", sa.String(length=1024), nullable=True),
        sa.Column("subtitle_ass_path", sa.String(length=1024), nullable=True),
        sa.Column("tts_audio_path", sa.String(length=1024), nullable=True),
        sa.Column("mixed_audio_path", sa.String(length=1024), nullable=True),
        sa.Column("output_video_path", sa.String(length=1024), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "speakers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("tts_voice_id", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("speakers")
    op.drop_table("episodes")
    op.drop_table("projects")
    # ### end Alembic commands ###
